name: Deploy to Surge

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build site
        run: pnpm run build

      - name: Upload built site
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to Surge
        id: deploy
        run: |
          DEPLOYMENT_DOMAIN="www.inflection.engineering"
          echo "url=https://$DEPLOYMENT_DOMAIN" >> $GITHUB_OUTPUT
          surge dist/ "$DEPLOYMENT_DOMAIN"

        env:
          SURGE_LOGIN: ${{ vars.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      - name: Record deployment
        uses: actions/github-script@v8
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'production',
              description: 'Deploy to production',
              auto_merge: false
            });

            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: 'success',
              environment_url: '${{ steps.deploy.outputs.url }}',
              description: 'Deployed production site'
            });
